# Generated by Django 5.2.6 on 2025-10-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='cnpj_loja',
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(default='Sem endereço', max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Loja'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
